apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event-service
  template:
    metadata:
      labels:
        app: event-service
    spec:
      containers:
      - name: event-service
        image: 476140239238.dkr.ecr.us-east-1.amazonaws.com/event-service:latest
        ports:
        - containerPort: 5000
        env:
        - name: DATABASE_URL
          value: postgresql://dbadmin:password123@eventdb.ce966q66a0se.us-east-1.rds.amazonaws.com:5432/eventdb
---
apiVersion: v1
kind: Service
metadata:
  name: event-service
spec:
  selector:
    app: event-service
  ports:
    - port: 80
      targetPort: 5000
  type: LoadBalancer
